# -*- coding: utf-8 -*-
"""2주차 연습문제

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_0WEvli8O7pd0V8nbxPnmMXuXCZBE1S
"""

#1. 숫자 5와 5.6을 임의의 변수에 할당하고 더한 후, 결과값을 출력하시오.

a = 5
b = 5.6
a + b

#2. "You are" 과 " so beautiful!" 이라는 두 문장을 변수에 할당하고 한 문장으로 출력하시오.

a = "You are"
b = " so beautiful!"
a + b

#3. "4"와 5를 임의의 변수에 할당하고 서로 더해서 결과값이 9가 나오도록 출력하시오.

a = "4"
b = 5
print(int("4") + b)

#4. 1과 1.5를 임의의 변수에 할당하고 누가 큰지 비교해서 결과가 True값을 가지도록 코드를 작성해라

a = 1
b = 1.5
a < b

#5. 2의 5제곱과 3을 2로 나눈 나머지의 수를 더하고 6을 곱한 결과를 출력해라

a = 2**5
b = 3
c = 2
(a + b % c)*6

#6. -10의 절대값과 5을 곱해서 6.7로 나눈 수를 출력해라

abs(-10)*5/6.7

#7. 두 변수를 이용하여 아래와 같이 출력해보시오.

# 실행 예시

# I like to learn python programming!!!

a = "I like to learn "
b = " python programming!!!"
a + b

#8. 5의 제곱을 python 코드로 나타내고 결과를 출력하시오.

a = 5
a**2

#9. BMW 5시리즈가  월 1,248,600원에 무이자 60개월 조건으로 판매되고 있습니다.
#총 금액을 계산한 후 화면에 출력하는  코드를 작성해 보세요.

BMW_5시리즈 = 1248600
총금액 = BMW_5시리즈 * 60
print(총금액)

#10. 숫자 125와 문자열 125가 같은지 비교하는 코드를 작성하고 화면에 같은지 출력하시오.

a = 125
b = "125"
a == b

